name: adaptive_extensions
description: >-
  Material Widgets to Cupertino Widget, this package provides some simple adaptive conversions to Cupertino.
version: 0.0.3
homepage: https://www.koriai.com

environment:
  sdk: '>=3.2.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

screenshots:
  - description: "Gif screenshots"
    path: images/screencast1.gif

topics:
  - ui
  - adaptive
  - widgets
  - theme